notes/urls.py
from django.urls import path
from .views import NoteListView, NoteDetailView, note_details

urlpatterns = [
    path('', NoteListView.as_view(), name='note'),
    # path('<slug>/', NoteDetailView.as_view(), name='note-details'),
    path('<slug>/', note_details, name='note-details'),
]

sajibnotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from . import settings
from .views import HomePage, about_page, contact_page, home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('about/', about_page, name='about'),
    path('contact/', include('contactforms.urls')),
    path('contacts/', contact_page, name='contacts'),
    path('note/', include('notes.urls')),
    path('project/', include('project.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

from account.models import Profile
from sajibnotes.helper import get_current_user

class Category(models.Model):
    name = models.CharField(max_length=30)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=15)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Note(models.Model):
    title = models.CharField(max_length=240)
    slug = models.SlugField(max_length=120, unique=True)
    photo = models.ImageField(upload_to='notes/')
    content = RichTextUploadingField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    is_delete = models.BooleanField(default=False)
    current_user = get_current_user
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, default=current_user)
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    email = models.EmailField()
    website = models.URLField(blank=True, null=True)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

project/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

from account.models import Profile
from sajibnotes.helper import get_current_user

class Category(models.Model):
    name = models.CharField(max_length=30)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=15)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Project(models.Model):
    title = models.CharField(max_length=240)
    slug = models.SlugField(max_length=120, unique=True)
    video_url = models.URLField()
    content = RichTextUploadingField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    is_delete = models.BooleanField(default=False)
    current_user = get_current_user
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, default=current_user)
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

templates/base/archives.html
<div class="sidebar-box ftco-animate">
    <h3 class="sidebar-heading">Archives</h3>
    <ul class="categories">
        <li>
            <a href="#">Decob14 2018 <span>(10)</span></a>
        </li>
        <li>
            <a href="#">September 2018 <span>(6)</span></a>
        </li>
        <li>
            <a href="#">August 2018 <span>(8)</span></a>
        </li>
        <li>
            <a href="#">July 2018 <span>(2)</span></a>
        </li>
        <li>
            <a href="#">June 2018 <span>(7)</span></a>
        </li>
        <li>
            <a href="#">May 2018 <span>(5)</span></a>
        </li>
    </ul>
</div>

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <title>{% block title %} {% endblock %}</title>
        {% include 'base/header.html' %}
      </head>
    <body>
        <div id="colorlib-page">
            <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
            {% include 'base/sidebar.html' %}
            <!-- END COLORLIB-ASIDE -->
            {% block content %} {% endblock %}
            <!-- END COLORLIB-MAIN -->
        </div>
        <!-- END COLORLIB-PAGE -->

        <!-- loader -->
        <div id="ftco-loader" class="show fullscreen">
            <svg class="circular" width="48px" height="48px">
                <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
                <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" />
            </svg>
        </div>

        {% include 'base/js.html' %}
    </body>
</html>

templates/base/header.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">

<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

<link rel="stylesheet" href="{% static 'css/aos.css' %}">

<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/base/js.html
{% load static %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/base/notes-sidebar.html
{% load static %}

<div class="col-xl-4 sidebar ftco-animate bg-light pt-5">
    <div class="sidebar-box pt-md-4">
        <form action="#" class="search-form">
            <div class="form-group">
                <span class="icon icon-search"></span>
                <input type="text" class="form-control" placeholder="Type a keyword and hit enter" />
            </div>
        </form>
    </div>
    <!-- Categories -->
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Note Categories</h3>
        <ul class="categories">
            {% if note_ctg %}
            {% for ctg in note_ctg %}
            <li>
                <a href="#">{{ ctg.name }} <span>({{ ctg.note_set.count }})</span></a>
            </li>
            {% endfor %}
            {% else %}
            <p>No Category Found</p>
            {% endif %}
        </ul>
    </div>
    <!-- Categories -->

    <!-- Popular Notes -->
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Popular Notes</h3>
        {% if popular_note %}
        {% for note in popular_note %}
        <div class="block-21 mb-4 d-flex">
            <a class="blog-img mr-4" style="background-image: url({% static 'images/image_1.jpg' %});"></a>
            <div class="text">
                <h3 class="heading"><a href="{% url 'note-details' note.slug %}">{{ note.title }}</a></h3>
                <div class="meta">
                    <div>
                        <a href="#"><span class="icon-calendar"></span>{{ note.published_date }}</a>
                    </div>
                    <div>
                        <a href="#"><span class="icon-person"></span>{{ note.author }}</a>
                    </div>
                    <div>
                        <a href="#"><span class="icon-chat"></span>{{ note.comment.count }}</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p>No Popular Note Found</p>
        {% endif %}
    </div>
    <!-- Popular Notes -->

    <!-- Tags -->
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Tag Cloud</h3>
        <ul class="tagcloud">
            {% if note_tag %}
            {% for tag in note_tag %}
            <a href="#" class="tag-cloud-link">{{ tag.name }}</a>
            {% endfor %}
            {% else %}
            <p>No Tags are Found</p>
            {% endif %}
        </ul>
    </div>
    <!-- Tags -->

    <div class="sidebar-box subs-wrap img py-4" style="background-image: url(images/bg_1.jpg);">
        <div class="overlay"></div>
        <h3 class="mb-4 sidebar-heading">Newsletter</h3>
        <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia</p>
        <form action="#" class="subscribe-form">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Email Address" />
                <input type="submit" value="Subscribe" class="mt-2 btn btn-white submit" />
            </div>
        </form>
    </div>

   {% include 'base/archives.html' %}

    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Paragraph</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut.</p>
    </div>
</div>

templates/base/project-sidebar.html
{% load static %}

<div class="col-xl-4 sidebar ftco-animate bg-light pt-5">
    <div class="sidebar-box pt-md-4">
        <form action="#" class="search-form">
            <div class="form-group">
                <span class="icon icon-search"></span>
                <input type="text" class="form-control" placeholder="Type a keyword and hit enter" />
            </div>
        </form>
    </div>
    <!-- Categories -->
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Project Categories</h3>
        <ul class="categories">
            {% if project_ctg %}
            {% for ctg in project_ctg %}
            <li>
                <a href="#">{{ ctg.name }} <span style="color: green;">({{ ctg.project_set.count }})</span></a>
            </li>
            {% endfor %}
            {% else %}
            <p>No Category Found</p>
            {% endif %}
        </ul>
    </div>
    <!-- Categories -->

    <!-- Popular Notes -->
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Popular Projects</h3>
        {% if popular_project %}
        {% for project in popular_project %}
        <div class="block-21 mb-4 d-flex">
            <a class="blog-img mr-4" style="background-image: url({% static 'images/image_1.jpg' %});"></a>
            <div class="text">
                <h3 class="heading"><a href="{% url 'project-details' project.slug %}">{{ project.title }}</a></h3>
                <div class="meta">
                    <div>
                        <a href="#"><span class="icon-calendar"></span>{{ project.published_date }}</a>
                    </div>
                    <div>
                        <a href="#"><span class="icon-person"></span>{{ project.author }}</a>
                    </div>
                    <div>
                        <a href="#"><span class="icon-chat"></span> 19</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p>No Project Found</p>
        {% endif %}
    </div>
    <!-- Popular Notes -->

    <!-- Tags -->
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Tag Cloud</h3>
        <ul class="tagcloud">
            {% if project_tag %}
            {% for tag in project_tag %}
            <a href="#" class="tag-cloud-link">{{ tag.name }}</a>
            {% endfor %}
            {% else %}
            <p>No Tags Found</p>
            {% endif %}
        </ul>
    </div>
    <!-- Tags -->

    <div class="sidebar-box subs-wrap img py-4" style="background-image: url(images/bg_1.jpg);">
        <div class="overlay"></div>
        <h3 class="mb-4 sidebar-heading">Newsletter</h3>
        <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia</p>
        <form action="#" class="subscribe-form">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Email Address" />
                <input type="submit" value="Subscribe" class="mt-2 btn btn-white submit" />
            </div>
        </form>
    </div>

   {% include 'base/archives.html' %}

    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Paragraph</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut.</p>
    </div>
</div>

templates/base/sidebar.html
{% load static %}
<aside id="colorlib-aside" role="complementary" class="js-fullheight">
    <nav id="colorlib-main-menu" role="navigation">
        <ul>
            <li class="colorlib-active"><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'note' %}">Notes</a></li>
            <li><a href="{% url 'project' %}">Project</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contacts' %}">Contact</a></li>
        </ul>
    </nav>
    <div class="colorlib-footer">
        <h1 id="colorlib-logo" class="mb-4"><a href="index.html" style="background-image: url({% static 'images/bg_1.jpg' %});">Sajib <span>Notes</span></a></h1>
        <div class="mb-4">
            <h3>Subscribe for newsletter</h3>
            <form action="#" class="colorlib-subscribe-form">
    <div class="form-group d-flex">
        <div class="icon"><span class="icon-paper-plane"></span></div>
      <input type="text" class="form-control" placeholder="Enter Email Address">
    </div>
  </form>
        </div>
        <p class="pfooter"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
    </div>
</aside> 